### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by mikebasdeo** [ModestosV/Simple-Calculator-DreamTeam#14]
[SP: 3]
[Priority: 1]
[Risk: high]

**Comment by ModestosV** [comment]
As proof, every member must create a dummy pull request from their development environment.

**Comment by ModestosV** [comment]
Every member of the team has successfully had a pull request approved.

**Comment by mehranhassani** [comment]
Did you put Jenkins login credentials in the repo?

**Comment by ModestosV** [comment]
We made it so that anyone can view the project and its builds, found here: http://138.197.130.216:8080/job/SimpleCalculator_2/

Would you like administrator privileges? If so, I can email you credentials?
