### ISSUE TITLE
Setup Testing Environment and Continuous Integration

### ISSUE THREAD

**Issue by mikebasdeo** [ModestosV/Simple-Calculator-DreamTeam#15]
[SP: 8]
[Priority: 1]
[Risk: high]

**Comment by ModestosV** [comment]
Every group member has installed a local Jenkins instance. We decided to host a remote instance of Jenkins that can be found at the following url: http://138.197.130.216:8080/job/SimpleCalculator_2/

**Comment by mikebasdeo** [comment]
Robolectric Testing working as of #10

**Comment by ModestosV** [comment]
Polling SCM still needed so that our Jenkins can auto-build on any changes to the main branch

**Comment by mikebasdeo** [comment]
Polling SCM is live. Any changes to the master branch will  refresh the build on Jenkins. See #31

**Comment by mehranhassani** [comment]
Put a label on UserStories

**Comment by marcdragon123** [comment]
Do you mean but a label "UserStories" on our issues?

**Comment by mehranhassani** [comment]
If they are user stories yes
