### ISSUE TITLE
Architecture Analysis

### ISSUE THREAD

**Issue by mikebasdeo** [ModestosV/Simple-Calculator-DreamTeam#16]
[SP: 8]
[Priority: 1]
[Risk: high]

**Comment by marcdragon123** [comment]
http://dreamteamsoen390.wikia.com/wiki/Pictures?file=Architecture_Diagram.jpg

**Comment by marcdragon123** [comment]
![architecture_diagram](https://user-images.githubusercontent.com/14812262/35602390-0bd2798a-0606-11e8-8672-ccd74d2a37c7.jpg)

**Comment by marcdragon123** [comment]
![architecture_diagram](https://user-images.githubusercontent.com/14812262/35602476-67ecb226-0606-11e8-8af5-b2710e9874b8.jpg)

**Comment by mehranhassani** [comment]
This is not really what we look for. Why do you have Jenkins and Github here? these are just tools.

**Comment by marcdragon123** [comment]
They are part of the CI and testing. Would you want them removed and just have the android phone? @mehranhassani

**Comment by ModestosV** [comment]
I am still a bit confused on the "Architectural Diagram". Did you mean that our diagram should look more like this: https://readerman1.files.wordpress.com/2015/07/layered-software-architecture-04.png or were you referring to the 4+1 Architectural View Model?

**Comment by mehranhassani** [comment]
CI and testing are not related to your code architecture. Your architecture should contain different components of the software, not the tools you use. CI is like your IDE. It makes your life easier. This is more like a deployment architecture.

**Comment by marcdragon123** [comment]
Perfect Thank you ^^

**Comment by noahcharbelhayek** [comment]
![architecture_diagram](https://user-images.githubusercontent.com/14878569/35745568-b38f24d6-0811-11e8-80dc-2cfabd458187.png)

**Comment by noahcharbelhayek** [comment]
This is our deployment architectural diagram, we don't have a server component so we are limited to the client device.

**Comment by marcdragon123** [comment]
Package Diagram

**Comment by marcdragon123** [comment]
![image](https://user-images.githubusercontent.com/14812262/36281883-4bbeae92-126d-11e8-8b7f-a4247ee15b6b.png)

**Comment by marcdragon123** [comment]
Class Diagram

![image](https://user-images.githubusercontent.com/14812262/36281946-7aaddfd4-126d-11e8-9a7b-1daef71301dc.png)

**Comment by marcdragon123** [comment]
Library Class Diagram

![image](https://user-images.githubusercontent.com/14812262/36282005-a7960652-126d-11e8-9495-f8cf64806d4d.png)
