### ISSUE TITLE
Implement Equation Solving

### ISSUE THREAD

**Issue by mikebasdeo** [ModestosV/Simple-Calculator-DreamTeam#18]
As a user, I want to input equations with brackets and multiple operators.

[SP: 34]
[Priority: 1]
[Risk: high]

**Comment by ModestosV** [comment]
Note: Current program returns 0 when any number is divided by 0. For accuracy, this should be changed to throw an error to avoid confusion when it comes to longer equations.

Example (Current implementation): 4 + (5/0) * 3 + 7 = 11
Example (Target implementation): 4 + (5/0) * 3 + 7 = ERROR

**Comment by ModestosV** [comment]
See #38 for the implementation of this feature. Basic testing is complete. More advanced testing is needed. Some minor bugs to fix, such as divisions by 0.

**Comment by mikebasdeo** [comment]
Math library is now editable for future features. #40

**Comment by ModestosV** [comment]
Testing is adequate as of #43 . Feature works as intended.
