### ISSUE TITLE
 Paste a Number

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#23]
As a user, I would like to paste numbers into the calculator from my clipboard.

[SP: 2]
[Priority: 6]
[Risk: medium]

**Comment by lambhunter0** [comment]
https://github.com/ModestosV/Simple-Calculator-DreamTeam/commit/8a15f9552c95d732e4504d5e0bdca7b3f20ec8c5

**Comment by ModestosV** [comment]
Issue is resolved, create separate issue if you would like to create a toast when a paste doesn't go through.

**Comment by lambhunter0** [comment]
![acceptance test 1](https://user-images.githubusercontent.com/10935055/37573773-c6b053b6-2af1-11e8-96a8-44e963348d88.png)
