### ISSUE TITLE
Save Calculator State

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#29]
As a user, I would like to save the current state of my entry and re-use saved equations.

[SP: 21]
[Priority: 1]
[Risk: high]

**Comment by marcdragon123** [comment]
Hey guys, I thought of a way to store the values on the calculator. There is an object called temp file on the android dev page. That is the way we could store the values?

**Comment by marcdragon123** [comment]
Done guys

**Comment by marcdragon123** [comment]
@NoahCF  and @Aboumicho Can you pull this branch and test this feature?

**Comment by ModestosV** [comment]
Pull request #39 completes this feature with relevant testing.
