### ISSUE TITLE
List Previous Entries

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#30]
As a user, I would like to see a list of my last 5 entries.

[SP: 21]
[Priority: 5]
[Risk: high]

**Comment by marcdragon123** [comment]
- [x] Front End display @Arkondoma 
- [x] Back-end saving files @Aboumicho 
- [x] File Manager to organize system @marcdragon123

**Comment by marcdragon123** [comment]
This issue is now closed with the merge of pull request #52. Issue closed.

**Comment by Arkondoma** [comment]
Mock-up of history view
![0](https://user-images.githubusercontent.com/11342755/37185727-c00daf3e-230f-11e8-8d1e-90f517752494.jpg)

**Comment by lambhunter0** [comment]
![screen shot 2018-03-19 at 5 02 16 pm](https://user-images.githubusercontent.com/10935055/37622159-54bf0bac-2b97-11e8-99d1-604e3c29e781.png)
