### ISSUE TITLE
Bug fix - History Section

### ISSUE THREAD

**Issue by marcdragon123** [ModestosV/Simple-Calculator-DreamTeam#62]
- Texts fall off screen after several inputs.

- [x] Limits number of inputs
- [x] Reorder to make new entries at the top

**Comment by ModestosV** [comment]
**Bugfix Needed** @marcdragon123 

- [x] Handle long inputs/outputs

**Comment by ModestosV** [comment]
@marcdragon123 not sure if it was fixed through implementation or a newer SDK, but long inputs/outputs are handled and don't break the screen on SDK27
