### ISSUE TITLE
Enhance Unit Conversion Layout

### ISSUE THREAD

**Issue by lambhunter0** [ModestosV/Simple-Calculator-DreamTeam#69]
As a user, I would like to also convert Temperatures, and have more units available. Furthermore, I would like to see the abbreviated units as well as the full name.

[SP: 13]
[Priority: 3]
[Risk: low]

**Comment by ModestosV** [comment]
- [x] Prototype the updated layout @Arkondoma 
- [x] Design the new layout with abbreviations @ModestosV @Arkondoma 
- [x] Implement the Temperature conversion @ModestosV
- [x]  Create and Implement Swap Button @Arkondoma @ModestosV #79 
- [x] Write UI and unit tests @ModestosV @Arkondoma  #80 
- [x] Write acceptance test @Arkondoma

**Comment by Arkondoma** [comment]
Mock-up for new unit conversion UI with new features
![image](https://user-images.githubusercontent.com/11342755/38270073-5aa7113a-3750-11e8-978e-9b83c9f26c02.png)

**Comment by Arkondoma** [comment]
Acceptance Test
![image](https://user-images.githubusercontent.com/11342755/38272625-bdd3f5c8-3757-11e8-9f63-4d538f3962a1.png)
