### ISSUE TITLE
Tabs for our 3 main activities

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#88]
Related to #68

**Comment by mikebasdeo** [comment]
![tabs](https://user-images.githubusercontent.com/9420573/38691128-e2f71fd6-3e4d-11e8-955e-87b8335d21db.png)

**Comment by mikebasdeo** [comment]
Some of the button colors need to be fixed, and the layouts need to be adjusted since the tabs take up some extra room at the top. 
[mike/tabs2](/ModestosV/Simple-Calculator-DreamTeam/commits/mike/tabs2)
