### ISSUE TITLE
Navigate with tabs

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#89]
Related to #68

**Comment by mikebasdeo** [comment]
![tabs](https://user-images.githubusercontent.com/9420573/38691046-a5333cca-3e4d-11e8-95a5-a76c5803ba48.png)

Branch in progress: [mike/tabs2](/ModestosV/Simple-Calculator-DreamTeam/commits/mike/tabs2)

**Comment by mikebasdeo** [comment]
[mike/tabs2](/ModestosV/Simple-Calculator-DreamTeam/commits/mike/tabs2)
