### ISSUE TITLE
Navigate with swipe

### ISSUE THREAD

**Issue by ModestosV** [ModestosV/Simple-Calculator-DreamTeam#90]
Related to #68

**Comment by mikebasdeo** [comment]
![tabs](https://user-images.githubusercontent.com/9420573/38691056-add94c98-3e4d-11e8-9646-d8980fcee33f.png)

Swipe works.

**Comment by mikebasdeo** [comment]
Some of the button colors need to be fixed, and the layouts need to be adjusted since the tabs take up some extra room at the top. 
[mike/tabs2](/ModestosV/Simple-Calculator-DreamTeam/commits/mike/tabs2)
